### ISSUE TITLE
Script does not yield essays

### ISSUE THREAD

**Issue by 676339784** [Nicholas-Swift/apstudynotes-Hacker#1]
Pretty inexperienced in regards to running scripts, but after running `python AP\ Study\ Notes\ Hacker.py`, I get [this](https://gist.github.com/676339784/725b36946ca82208d67c8726641e6947). Is it possible to see if I am missing a module or anything of the such?

**Comment by Nicholas-Swift** [comment]
It might be because I built this in Python 3 rather than 2.7, but I'm taking a look now

**Comment by Nicholas-Swift** [comment]
So the problem is that this "https://www.apstudynotes.org{u'href': u'/stanford/stanford-short-questions/" should be this "https://www.apstudynotes.org/stanford/stanford-short-questions/", taking a look now into why it might be different

**Comment by Nicholas-Swift** [comment]
In the second for loop in the

"Get the URLs to apstudynotes.org's 141 essays." block, add 

urlList[i] = urlList[i].replace("{u'href': u'", "") before the print.

That should work. Please message me with regards to how it goes! I'd also like to thank you for also actually using my code and taking a look at my repository :).

**Comment by 676339784** [comment]
Haha, I should be the one thanking you.

Now everything works now! Just had to run it through python3 as you said.

**Comment by Nicholas-Swift** [comment]
Haha sweet, glad everything worked out :D
